### ISSUE TITLE
File already exists?

### ISSUE THREAD

**Issue by wosym** [0xf4b1/hearthstone-linux#60]
Looks like something broke:

`0% 0/4044 [00:00<?, ?file/s]Error: <...>/hearthstone-linux/hearthstone/BlizzardBrowser/BlizzardBrowser.app/Contents/Frameworks/BlizzardBrowser Helper (GPU).app/Contents/Info.plist already exists. Not overwriting.`

Also tried deleting the venv folder and starting from scratch. Same  problem.

Experienced the issue on two computers simultaneously: one on Arch, the other on Ubuntu.

**Comment by rflandau** [comment]
I had this issue as well on Debian Bookworm, but a full re-craft (by junking everything in the hearthstone-linux/hearthstone/ directory) solved it for me.

**Comment by wosym** [comment]
@0xf4b1 Was the bug fixed? Because yes, deleting the folder fixed it. But Downloading the entire 30GB again every single update... is not workable for many people.

**Comment by alterNERDtive** [comment]
```bash
> du -sh BlizzardBrowser                                                                     master
199M	BlizzardBrowser
```
How is that 30GB?

**Comment by 0xf4b1** [comment]
yes, the problem is fixed with this change. The macOS client now contains the new BlizzardBrowser folder and the installation with keg fails if some file already exists. In case of updating what happens is that that keg downloads all changed files into its repository in the `.ngdp` inside the hearthstone directory from which it installs the most recent version, so it does not redownload everything because we never delete the files inside ngdp.
