### ISSUE TITLE
Shop is always closed

### ISSUE THREAD

**Issue by Kangaroux** [0xf4b1/hearthstone-linux#81]
client.config
```
Aurora.ClientCheck=false
Aurora.Env.Override=1
Aurora.Env=us.actual.battle.net
Localization.Locale=enUS
```

```
OS: Kubuntu 24.04.1 LTS x86_64 
Kernel: 6.8.0-49-generic 
Uptime: 5 days, 17 hours, 18 mins 
Packages: 2490 (dpkg), 21 (flatpak), 6 (snap) 
Shell: bash 5.2.21 
Resolution: 2560x1440, 2560x1440 
DE: Plasma 5.27.11 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 7 5700X3D (16) @ 3.000GHz 
GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT 
Memory: 24782MiB / 32000MiB
```

**Comment by Kangaroux** [comment]
First paragraph of the readme says the shop is always closed, so this seems like a known limitation rather than a bug

**Comment by alterNERDtive** [comment]
I would assume(!) that the shop only works if Battle.net is actually running in the background. It is not if you use this.

**Comment by 0xf4b1** [comment]
Yep, this is correct, it's expected not to work and never worked before. I think it's not about the Battle.net launcher but most likely because of a missing native library, namely `blz_commerce_sdk_plugin`, and this would be needed to be reimplemented by analyzing/decompiling the dylib from mac, dll from windows, or maybe the arm version from the android version which I believe someone started in #33 but never really completed.
